### ISSUE TITLE
fleet_type = 4 = Predator to create M2

### ISSUE THREAD

**Issue by k-doering-NOAA** [nmfs-stock-synthesis/stock-synthesis#45]
Imported from redmine, Issue [#67572](https://vlab.ncep.noaa.gov/redmine/issues/67572)
 Opened by @RickMethot on 2019-08-21
Status when imported: New
 
requirements could include:
1.  input of consumption amount in biomass or numbers
2.  input predator abundance as a "survey" of effort
3.  functional form to relate "F" by the predator to the predator abundance
4.  composition data is from gut contents

A predator fleet will look a lot like a bycatch fleet.  What's different?

Nice to be able to tune the F to match the discard amount for both.

Perhaps change model so that catch entries for a bycatch fleet are treated as total catch and SS tunes to them just like it does for retained catch of fleet type=1, but still need to generate a F in designated years for which there is no input catch amount.

**Comment by Rick-Methot-NOAA** [comment]
This issue became actively developed on 8/31/2021 in order to provide a means to treat mortality caused by Red Tide as a part of M rather than part of F.  Because if it is part of F, then the overall F reporting becomes distorted (see #200).

The approach being implemented is as follows:
1.  designate fleet as a predator  type 4
2.  nothing else needed in data file
3.  control file:  then at end of MG parameters creates a M2 parameter for each predator fleet.
4.  In the test example, I gave that parameter 2 blocks to make it do exactly (using M2) what original approach did with F
4.  selectivity is specified normally and used to distribute the M2 across ages
5.  output of the resultant M is best viewed with the Z=M table at end of report.sso

Later I will amend the survey CPUE section so an index can be used to inform the M2 over time.
@nathanvaughan-NOAA - Nathan can comment here.

**Comment by nathanvaughan-NOAA** [comment]
Thanks Rick,
        I was able to get the basic setup running with Gag. A brief rundown of the changes I made are
1) Adjust fleet type from 2 to 4 for the red tide fleet in the dat file
2) Remove the discard fleet specification row from the dat file
3) Add an M2 parameter to the control file for the red tide fleet fixed at zero, with TV blocks enabled and set up to replace the base param in each block. 
4) Added a new TV block that has three periods specified as 2005 2005 2014 2014 2018 2018 to the control file
5) Added 3 TV params to the control file estimated in phase 4

My first impression is that the model appears to be running correctly. 
The three M estimates are very close to the Fs estimated by the previous bycatch fleet approach. 
The new M estimates are also easily available in the last column of the TIME_SERIES section of the report file and in the parameter estimates section.
  
I still need to develop a seasonal version of the model to see if anything changes.
I also haven't dug deeper into the results to confirm nothing is off. 
I will also test the new version with our projection software and see how it works.

Thanks again @Rick-Methot-NOAA  for getting this running so quickly.

**Comment by Rick-Methot-NOAA** [comment]
Thanks Nathan.  Those are exactly the steps I followed for red grouper.

The trick in doing this is that I could not add M2 right after getting the
usual M1 calculated.

Instead, the code for M2 is further down in the code and is in the season
loop so it can use results of makefishselex() to spread the M2 across ages.

So the sequence goes:
1.  calculated natM()  using  get_natmort();
2.  store copy:      natM_M1=natM;  // where each is matrix with
dimensions of season, morph-sex, and age.
3.  enter season loop and update selectivity with makefishselex()
4.  then if predators exist, update that season's M and dependent
quantities:
              natM(s,gpi)=natM_M1(s,gpi)+pred_M2(f1,styr-2)*sel_al_3(s,g,f);
              surv1(s,gpi)=mfexp(-natM(s,gpi)*seasdur_half(s));
              surv2(s,gpi)=square(surv1(s,gpi));

The sequence above appears 3 times in the code:  for start year (hence for
initial equilibrium), for each year of time series, and for each year of
the forecast.

I need to double check some flags used to skip over the calculations if M
and Growth parameters are not time-varying.  M2 needs to get updated if
either M or selectivity or growth is updated.  So I think it safest to
always update it annually if predators exist to avoid too many more IF
statements.

**Comment by k-doering-NOAA** [comment]
Could more explicit parameter names besides M1 and M2 be used? Especially if these are reported back to the user... I personally always forget what is meant by these

**Comment by Rick-Methot-NOAA** [comment]
M2 is an usual and accustomed term in the multispecies modeling world.
M=M1+M2 where M2 is the component of M due explicitly to predation.

**Comment by k-doering-NOAA** [comment]
Right, but that still doesn't make it a great name! But I guess we live with Type I and Type II error in statistics... I think someone brought up using more explicit names than M1 and M2 in a discussion at CAPAM, also.

**Comment by Rick-Methot-NOAA** [comment]
We're on the cutting edge, so we can initiate the change!
We can call the parameter _predM

We should develop some output to show base M, predM, combined M, and
combined M+F (e.g. Z).

**Comment by k-doering-NOAA** [comment]
Great ideas, Rick - are all these values reported yet from SS? Or does that still need to be added?  Happy to help out with new r4ss plots, potentially.

 Hmm, trying to think of an informative name for M_base, I wonder if that could be confused with calling something the "base parameter value" when using time varying values? Giving this more thought, I can see why multispecies community defaulted to M1 and M2. Now I'm curious to hear others' thoughts on naming components of natural mortality, maybe @christinestawitz-NOAA who has done more ecosystem/multispecies work?

**Comment by Rick-Methot-NOAA** [comment]
Working with Max we realized that the pred_M2 for styr-1 (initial equilibrium) needs better controls.

**Comment by ChristineStawitz-NOAA** [comment]
I'm working on naming with Kelli now and I can't say I have a good solution yet beyond the concept of [self-documenting code](https://en.wikipedia.org/wiki/Self-documenting_code) such that it is obvious what each one is. For example, base_natM, multispp_natM, singlespp_natM. If you are changing it in Stock Synthesis might be worth a longer chat now so we can be consistent with future names in FIMS.

I also like synchronizing the name with r4ss (my spreadsheet says that is natM unless I'm outdated).

**Comment by Rick-Methot-NOAA** [comment]
Thanks Christine.  I am not ready to revamp the entire internal naming conventions for Synthesis, but will consider changes in future to attain better alignment with protocols developed by FIMS.  Right now, if pred_M2 is used the natM is updated to include it.  Someone will eventually want easy access to base_natM, so I will create that now.

**Comment by Rick-Methot-NOAA** [comment]
While working with Max on vendance application, realized that need to calculate the total consumption by each M2 fleet.  This can be done at same time as the other catch for fishing fleets are calculated.
Will store this as discard so the observed total consumption amounts can be entered as discard.

So, three capabilities will be developed:
a.  enter M2 as env driver:  So M2 = 0.0 + env_link_parm*M2_indicator
b.  enter total M2 consumption (by fleet):  using total kill and  M2/Z
c.   enter survey of M2 intensity:   enter predator abundance as a survey of M2 using same capability as current survey of F approach

**Comment by Rick-Methot-NOAA** [comment]
implement the above:
total consumption by each predator is now stored in exp_disc where SS can create logL relative to input of consumption amounts

pred_M2 parameter is mapped into survey expected values using survey_type==2  (survey of F).  Exept in this case it is not a F, it is M2.

Set up M2 for vendance model as a random dev and seemed to run fine, although with rather high biomass and low F and low M2
pushing this up to github

**Comment by nathanvaughan-NOAA** [comment]
Hey Rick,
     I'm still working through the predator fleet testing with Gag. I was able to get it up and running once I figured out the surveys were running in month 7 and if you don't have any catch in that season everything returns nulls. The first potential forecasting error I have noticed is that fixed forecast inputs for retained catch are not being matched exactly in the report time_series section outputs. I'll let you know when I have an idea what is causing it or when I identify further issues. 

example:
forecast file input
#year    seas   fleet   Catch        basis   
2020	3	1	73.786623	3	#MT
2020	3	2	133.690317	3	#MT
2020	3	3	2.611	3	#Numbers
2020	3	4	37.60773933	3	#Numbers
2020	3	5	305.4019118	3	#Numbers

achieved values
year     seas    fleet    Catch
2020    3         1         73.0806
2020    3        2        133.645
2020    3        3        2.60063
2020    3        4        37.6488
2020    3        5        266.061

For most fleets, the results are very close but for fleet 5 they seem a good deal off (before the pred fleet and season change all the achieved values were identical to the target values).

I also noticed that the way seasons are set up seems to have a significant impact on estimated red tide mortality rates. I assume this is due to the variable timing between the surveys and the landings based on the season setup. This seems like a sensitivity we may need to dig into more for future analyses. 

I have put the completed run for Gag with 4 seasons up on google drive if that helps. My runs were done with the original exe file before your recent commits, if those were expected to fix some of these issues I can rerun the tests.

Cheers,
Nathan

**Comment by nathanvaughan-NOAA** [comment]
https://drive.google.com/drive/u/1/folders/10qPS48uP6KfbQPo3aPBSghRa6Wrccs4i

here is the link to google drive Gag run.

**Comment by Rick-Methot-NOAA** [comment]
find need to add seasonality.
So now if nseas>1, add a season multiplier for each season.
#  M2 parameter for each predator fleet
 0 4 0.283 0.2 0.8 0 -3 0 5 1991 2018 2 1 2 # PredM2_1
 0 10 1 1 1 0 -1 0 0 0 0 0 0 0 # PredM2_1_s1
 0 10 1.12491 1 1 0 4 0 5 1991 2018 4 0 0 # PredM2_1_s2
 0 10 1.40781 1 1 0 4 0 5 1991 2018 4 0 0 # PredM2_1_s3
 0 10 1.80095 1 1 0 4 0 5 1991 2018 4 0 0 # PredM2_1_s4
#
# timevary MG parameters 
#_ LO HI INIT PRIOR PR_SD PR_type  PHASE
 1e-05 2.4 0.231134 0.2 0.8 0 3 # PredM2_1_BLK1repl_1990
 0.0001 2 1.7 0.5 0.5 6 -5 # PredM2_1_dev_se
 -0.99 0.99 0 0 0.5 6 -6 # PredM2_1_dev_autocorr
 0.0001 2 1.7 0.5 0.5 6 -5 # PredM2_1_s2_dev_se
 -0.99 0.99 0 0 0.5 6 -6 # PredM2_1_s2_dev_autocorr
 0.0001 2 1.7 0.5 0.5 6 -5 # PredM2_1_s3_dev_se
 -0.99 0.99 0 0 0.5 6 -6 # PredM2_1_s3_dev_autocorr
 0.0001 2 1.7 0.5 0.5 6 -5 # PredM2_1_s4_dev_se
 -0.99 0.99 0 0 0.5 6 -6 # PredM2_1_s4_dev_autocorr

**Comment by k-doering-NOAA** [comment]
@Rick-Methot-NOAA should this be marked resolved?

**Comment by Rick-Methot-NOAA** [comment]
just realized that predator is a fleet, so potentially could be ara-specific.  But currently the M2 mortality is not implemented with an area-specific capability.

**Comment by Rick-Methot-NOAA** [comment]
have not worked on the area-specific M2, which will take some work.

While working with another user found two issues:
M2 was not playing well with natM_type=3 (empirical M input).
Also noticed that a situation could occur in which M2 was re-added to the total M each year; which is bad.

Fixed both of above by saving initial calculation of natM to natM_M1, then adding M2 later if predators are used.
